jmix_animate.j_animation = Animation
jmix_animate.j_animation.bounce=Attention Seekers / Bounce
jmix_animate.j_animation.flash=Attention Seekers / Flash
jmix_animate.j_animation.headShake=Attention Seekers / Head Shake
jmix_animate.j_animation.heartBeat=Attention Seekers / Heart Beat
jmix_animate.j_animation.jello=Attention Seekers / Jello
jmix_animate.j_animation.pulse=Attention Seekers / Pulse
jmix_animate.j_animation.rubberBand=Attention Seekers / Rubber Band
jmix_animate.j_animation.shakeX=Attention Seekers / Shake X
jmix_animate.j_animation.shakeY=Attention Seekers / Shake Y
jmix_animate.j_animation.swing=Attention Seekers / Swing
jmix_animate.j_animation.tada=Attention Seekers / Tada
jmix_animate.j_animation.wobble=Attention Seekers / Wobble
jmix_animate.j_animation.backInDown=Back Entrances / Down
jmix_animate.j_animation.backInLeft=Back Entrances / Left
jmix_animate.j_animation.backInRight=Back Entrances / Right
jmix_animate.j_animation.backInUp=Back Entrances / Up
jmix_animate.j_animation.bounceIn=Bouncing Entrances / In
jmix_animate.j_animation.bounceInDown=Bouncing Entrances / Down
jmix_animate.j_animation.bounceInLeft=Bouncing Entrances / Left
jmix_animate.j_animation.bounceInRight=Bouncing Entrances / Right
jmix_animate.j_animation.bounceInUp=Bouncing Entrances / Up
jmix_animate.j_animation.fadeIn=Fading Entrances / In
jmix_animate.j_animation.fadeInBottomLeft=Fading Entrances / Bottom Left
jmix_animate.j_animation.fadeInBottomRight=Fading Entrances / Bottom Right
jmix_animate.j_animation.fadeInDown=Fading Entrances / Down
jmix_animate.j_animation.fadeInDownBig=Fading Entrances / Down Big
jmix_animate.j_animation.fadeInLeft=Fading Entrances / Left
jmix_animate.j_animation.fadeInLeftBig=Fading Entrances / Left Big
jmix_animate.j_animation.fadeInRight=Fading Entrances / Right
jmix_animate.j_animation.fadeInRightBig=Fading Entrances / Right Big
jmix_animate.j_animation.fadeInTopLeft=Fading Entrances / Top Left
jmix_animate.j_animation.fadeInTopRight=Fading Entrances / Top Right
jmix_animate.j_animation.fadeInUp=Fading Entrances / Up
jmix_animate.j_animation.fadeInUpBig=Fading Entrances / Up Big
jmix_animate.j_animation.flipInX=Flippers / Flip In X
jmix_animate.j_animation.flipInY=Flippers / Flip In Y
jmix_animate.j_animation.jackInTheBox=Specials / Jack In The Box
jmix_animate.j_animation.lightSpeedInLeft=Lightspeed / In Left
jmix_animate.j_animation.lightSpeedInRight=Lightspeed / In Right
jmix_animate.j_animation.rollIn=Specials / Roll In
jmix_animate.j_animation.rotateIn=Rotating Entrances / In
jmix_animate.j_animation.rotateInDownLeft=Rotating Entrances / Down Left
jmix_animate.j_animation.rotateInDownRight=Rotating Entrances / Down Right
jmix_animate.j_animation.rotateInUpLeft=Rotating Entrances / Up Left
jmix_animate.j_animation.rotateInUpRight=Rotating Entrances / Up Right
jmix_animate.j_animation.slideInDown=Sliding Entrances / Down
jmix_animate.j_animation.slideInLeft=Sliding Entrances / Left
jmix_animate.j_animation.slideInRight=Sliding Entrances / Right
jmix_animate.j_animation.slideInUp=Sliding Entrances / Up
jmix_animate.j_animation.zoomIn=Zoom Entrances / In
jmix_animate.j_animation.zoomInDown=Zoom Entrances / Down
jmix_animate.j_animation.zoomInLeft=Zoom Entrances / Left
jmix_animate.j_animation.zoomInRight=Zoom Entrances / Right
jmix_animate.j_animation.zoomInUp=Zoom Entrances / Up
jmix_animate.j_animation.backOutDown=Back Exits / Down
jmix_animate.j_animation.backOutLeft=Back Exits / Left
jmix_animate.j_animation.backOutRight=Back Exits / Right
jmix_animate.j_animation.backOutUp=Back Exits / Up
jmix_animate.j_animation.bounceOut=Bouncing Exits / Out
jmix_animate.j_animation.bounceOutDown=Bouncing Exits / Down
jmix_animate.j_animation.bounceOutLeft=Bouncing Exits / Left
jmix_animate.j_animation.bounceOutRight=Bouncing Exits / Right
jmix_animate.j_animation.bounceOutUp=Bouncing Exits / Up
jmix_animate.j_animation.fadeOut=Fading Exits / Out
jmix_animate.j_animation.fadeOutBottomLeft=Fading Exits / Bottom Left
jmix_animate.j_animation.fadeOutBottomRight=Fading Exits / Bottom Right
jmix_animate.j_animation.fadeOutDown=Fading Exits / Down
jmix_animate.j_animation.fadeOutDownBig=Fading Exits / Down Big
jmix_animate.j_animation.fadeOutLeft=Fading Exits / Left
jmix_animate.j_animation.fadeOutLeftBig=Fading Exits / Left Big
jmix_animate.j_animation.fadeOutRight=Fading Exits / Right
jmix_animate.j_animation.fadeOutRightBig=Fading Exits / Right Big
jmix_animate.j_animation.fadeOutTopLeft=Fading Exits / Top Left
jmix_animate.j_animation.fadeOutTopRight=Fading Exits / Top Right
jmix_animate.j_animation.fadeOutUp=Fading Exits / Up
jmix_animate.j_animation.fadeOutUpBig=Fading Exits / Up Big
jmix_animate.j_animation.flip=Flippers / Flip
jmix_animate.j_animation.flipOutX=Flippers / Flip Out X
jmix_animate.j_animation.flipOutY=Flippers / Flip Out Y
jmix_animate.j_animation.hinge=Specials / Hinge
jmix_animate.j_animation.lightSpeedOutLeft=Lightspeed / Out Left
jmix_animate.j_animation.lightSpeedOutRight=Lightspeed / Out Right
jmix_animate.j_animation.rollOut=Specials / Roll Out
jmix_animate.j_animation.rotateOut=Rotating Exits / Out
jmix_animate.j_animation.rotateOutDownLeft=Rotating Exits / Down Left
jmix_animate.j_animation.rotateOutDownRight=Rotating Exits / Down Right
jmix_animate.j_animation.rotateOutUpLeft=Rotating Exits / Up Left
jmix_animate.j_animation.rotateOutUpRight=Rotating Exits / Up Right
jmix_animate.j_animation.slideOutDown=Sliding Exits / Down
jmix_animate.j_animation.slideOutLeft=Sliding Exits / Left
jmix_animate.j_animation.slideOutRight=Sliding Exits / Right
jmix_animate.j_animation.slideOutUp=Sliding Exits / Up
jmix_animate.j_animation.zoomOut=Zoom Exits / Out
jmix_animate.j_animation.zoomOutDown=Zoom Exits / Down
jmix_animate.j_animation.zoomOutLeft=Zoom Exits / Left
jmix_animate.j_animation.zoomOutRight=Zoom Exits / Right
jmix_animate.j_animation.zoomOutUp=Zoom Exits / Up
jmix_animate.j_animationDelay=Delay in seconds (0-30)
jmix_animate.j_animationDelayUsage.delayBeforeAnimation=Wait before starting the animation
jmix_animate.j_animationDelayUsage.delayBeforeDisplay=Wait before displaying the component
jmix_animate.j_animationDelayUsage=How to use delay?
jmix_animate.j_animationDuration=Duration (in s)
jmix_animate.j_animationIterationCount.1=1
jmix_animate.j_animationIterationCount.2=2
jmix_animate.j_animationIterationCount.3=3
jmix_animate.j_animationIterationCount.infinite=Infinite (WCAG 2.2.2 - decorative use only)
jmix_animate.j_animationIterationCount=Iteration
jmix_animate=Add animation
